name: readability
description: A new Flutter project.
version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  path_provider:
  video_player:
  camera:

flutter:
  uses-material-design: true

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.2.0 <2.0.0"